config/routes.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :hikes do
    resource :map, only: :show
    resources :likes, only: %w[create destroy]
  end

  resources :users, only: :index do
    resources :hikes, only: :index, controller: :user_hikes
  end

  resources :configurations do
    get :ios_v1, on: :collection
    get :android_v1, on: :collection
  end

  root "hikes#index"
end

app/controllers/likes_controller.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    hike = Hike.find(params[:hike_id])
    hike.likes.find_or_create_by!(user: current_user)
    redirect_to hike
  end

  def destroy
    hike = Hike.find(params[:hike_id])
    hike.likes.find_by(user: current_user)&.destroy!
    redirect_to hike
  end
end

app/views/likes/_like.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<% if user_signed_in? %>
  <% if like.present? %>
    <%= button_to hike_like_path(hike, like), method: :delete, class: "btn btn-link icon-link link-danger link-underline-opacity-0 d-flex align-items-baseline gap-2 ps-1" do %>
      <i class="bi bi-heart-fill"></i>
      <span class="text-secondary ms-1"><%= pluralize(hike.likes_count, "like") %></span>
    <% end %>
  <% else %>
    <%= button_to hike_likes_path(hike), class: "btn btn-link icon-link link-secondary link-underline-opacity-0 d-flex align-items-baseline gap-2 ps-1" do %>
      <i class="bi bi-heart"></i>
      <span class="text-secondary ms-1"><%= pluralize(hike.likes_count, "like") %></span>
    <% end %>
  <% end %>
<% else %>
  <span class="text-secondary ms-1"><%= pluralize(hike.likes_count, "like") %></span>
<% end %>