config/routes.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :hikes do
    resource :map, only: :show
    resources :likes, only: %w[create destroy]
  end

  resources :users, only: :index do
    resources :hikes, only: :index, controller: :user_hikes
  end

  resources :configurations do
    get :ios_v1, on: :collection
    get :android_v1, on: :collection
  end

  root "hikes#index"
end

app/models/user.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
class User < ApplicationRecord
  has_secure_password

  has_many :hikes
  has_many :hike_likes
  has_many :liked_hikes, through: :hike_likes, source: :hike

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  normalizes :email, with: -> { _1.strip.downcase }
end

app/controllers/users_controller.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
class UsersController < ApplicationController
  def index
    @users = User.order(:created_at)
  end
end

app/views/users/_user.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= link_to user_hikes_path(user), class: "list-group-item list-group-item-action py-3 py-md-4" do %>
  <div class="row align-items-top">
    <div class="col pe-0">
      <h2 class="h5"><%= user.name %></h2>

      <div class="ms-auto">
        <p class="text-muted small">Joined on <%= user.created_at.strftime("%b %d") %></p>
      </div>

      <p class="line-clamp-2 text-body-secondary mb-0"><%= pluralize user.hikes_count, "hike" %></p>
    </div>

    <div class="col d-md-none flex-grow-0 flex-shrink-1 px-2 my-auto">
      <i class="bi bi-chevron-right text-body-tertiary"></i>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= render "shared/header", title: "Hikers" %>

<% if @users.any? %>
  <div class="container list-group list-group-flush px-0">
    <%= render @users %>
  </div>
<% else %>
  <p class="container">No hikers, yet.</p>
<% end %>