config/routes.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :hikes do
    resource :map, only: :show
    resources :likes, only: %w[create destroy]
  end

  resources :users, only: :index do
    resources :hikes, only: :index, controller: :user_hikes
  end

  resources :configurations do
    get :ios_v1, on: :collection
    get :android_v1, on: :collection
  end

  root "hikes#index"
end

app/views/shared/_flash.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<% if flash.notice.present? %>
  <div class="container my-4">
    <div class="alert alert-primary" role="alert">
      <%= flash.notice %>
    </div>
  </div>
<% end %>

<% if flash.alert.present? %>
  <div class="container my-4">
    <div class="alert alert-danger" role="alert">
      <%= flash.alert %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>

<% content_for :title, title %>

<div class="container d-hotwire-native-none">
  <h1 class="my-4 pt-md-4"><%= title %></h1>
</div>

app/views/shared/_navbar.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>

<nav class="navbar bg-body-tertiary d-hotwire-native-none">
  <div class="container">
    <%= link_to "Hiking journal", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse pb-2" id="navbar">
      <ul class="navbar-nav me-auto pb-">
        <li class="nav-item">
          <%= link_to "Hikes", hikes_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Hikers", users_path, class: "nav-link" %>
        </li>
      </ul>

      <hr class="border-1 border-secondary border-opacity-50">
      <% if user_signed_in? %>
        <%= link_to "Sign out", session_path, class: "nav-link",
          "data-turbo-method": "delete" %>
      <% else %>
        <%= link_to "Sign in", new_session_path, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</nav>