config/routes.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :hikes do
    resource :map, only: :show
    resources :likes, only: %w[create destroy]
  end

  resources :users, only: :index do
    resources :hikes, only: :index, controller: :user_hikes
  end

  resources :configurations do
    get :ios_v1, on: :collection
    get :android_v1, on: :collection
  end

  root "hikes#index"
end

app/models/hike.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
class Hike < ApplicationRecord
  validates :name, :description, presence: true

  belongs_to :user, counter_cache: true

  has_many :likes, class_name: "HikeLike"
  has_many :likers, through: :likes, source: :user

  has_one_attached :image
end

app/controllers/hikes_controller.rb
#---
# Excerpted from "Hotwire Native for Rails Developers",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/jmnative for more book information.
#---
class HikesController < ApplicationController
  before_action :authenticate_user!, except: %w[index show]

  def index
    @hikes = Hike.order(created_at: :desc)
  end

  def show
    @hike = Hike.find(params[:id])
    @like = @hike.likes.find_by(user: current_user)
  end

  def new
    @hike = Hike.new
  end

  def edit
    @hike = current_user.hikes.find(params[:id])
  end

  def create
    @hike = Hike.new(hike_params)
    if @hike.save
      redirect_to @hike, notice: "Hike added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @hike = current_user.hikes.find(params[:id])
    if @hike.update(hike_params)
      redirect_to @hike, notice: "Hike updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.hikes.find(params[:id]).destroy
    redirect_to hikes_path, notice: "Hike deleted."
  end

  private

  def hike_params
    params
      .require(:hike)
      .permit(:name, :description, :image, :latitude, :longitude)
      .merge(user: current_user)
  end
end

app/views/hikes/_form.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<% if hike.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p class="alert-heading fw-semibold mb-1">
      Please fix these issues to add your hike:
    </p>
    <ul class="mb-0">
      <% hike.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: hike, class: "row g-3 mt-1" do |form| %>
  <div>
    <div class="d-flex align-items-baseline justify-content-between">
      <%= form.label :name, class: "form-label" %>

      <% if hike.persisted? %>
        <%= link_to hike,
          class: "btn btn-sm btn-link text-danger text-decoration-none py-0",
          data: {
            turbo_confirm: "Are you sure?",
            turbo_method: "delete"
          } do %>
          <i class="bi bi-trash"></i>
          Delete hike
        <% end %>
      <% end %>
    </div>

    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control", rows: 8 %>
  </div>

  <div>
    <%= form.label :image, class: "form-label" %>

    <% if hike.image.attached? %>
      <%= image_tag hike.image, class: "img-thumbnail" %>
      <%= form.hidden_field :image, value: hike.image.signed_id %>
    <% end %>

    <%= form.file_field :image,
      accept: "image/jpg,image/jpeg,image/png",
      class: "form-control mt-2" %>
  </div>

  <div>
    <%= form.label :coordinates, class: "form-label" %>

    <div class="row">
      <div class="col">
        <%= form.number_field :latitude, class: "form-control",
          min: -90, max: 90, step: 0.000001 %>
      </div>
      <div class="col">
        <%= form.number_field :longitude, class: "form-control",
          min: -180, max: 180, step: 0.000001 %>
      </div>
    </div>
  </div>

  <div class="d-grid d-sm-flex justify-content-sm-end mt-4">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/hikes/_hike.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= link_to hike, class: "list-group-item list-group-item-action py-3 py-md-4" do %>
  <div class="row align-items-top">
    <div class="col pe-0">
      <h2 class="h5"><%= hike.name %></h2>

      <div class="ms-auto">
        <p class="text-muted small">
          Added on <%= hike.created_at.strftime("%b %d") %>
        </p>
      </div>

      <p class="line-clamp-2 text-body-secondary mb-0">
        <%= hike.description %>
      </p>
    </div>

    <div class="col d-md-none flex-grow-0 flex-shrink-1 px-2 my-auto">
      <i class="bi bi-chevron-right text-body-tertiary"></i>
    </div>
  </div>
<% end %>

app/views/hikes/edit.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= render "shared/header", title: "Edit hike" %>

<div class="container">
  <%= render "form", hike: @hike %>
</div>

app/views/hikes/index.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= render "shared/header", title: "Hikes" %>

<% if @hikes.any? %>
  <div class="container list-group list-group-flush px-0">
    <%= render @hikes %>
  </div>
<% else %>
  <p class="container">No hikes, yet.</p>
<% end %>

<div class="container d-flex justify-content-between gap-2 mt-4">
  <% if user_signed_in? %>
    <%= link_to "Add a hike", new_hike_path,
      class: "btn btn-primary flex-grow-1 flex-sm-grow-0" %>

    <%= link_to "Sign out", session_path,
        class: "btn btn-outline-danger d-none d-hotwire-native-block",
        data: {
        turbo_method: "delete",
        turbo_confirm: "Sign out?"
        } %>
  <% else %>
    <div class="flex-grow-1">
      <%= link_to "Sign in", new_session_path,
        class: "btn btn-outline-primary d-none d-hotwire-native-block" %>
    </div>
  <% end %>
</div>

app/views/hikes/new.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= render "shared/header", title: "Add a hike" %>

<div class="container">
  <%= render "form", hike: @hike %>
</div>

app/views/hikes/show.html.erb
<%#
 #   Excerpted from "Hotwire Native for Rails Developers",
 #   published by The Pragmatic Bookshelf.
 #   Copyrights apply to this code. It may not be used to create training material,
 #   courses, books, articles, and the like. Contact us if you are in doubt.
 #   We make no guarantees that this code is fit for any purpose.
 #   Visit https://pragprog.com/titles/jmnative for more book information.
%>
<%= render "shared/header", title: @hike.name %>

<div class="container">
  <% if @hike.image.attached? %>
    <%= image_tag @hike.image, class: "img-fluid rounded" %>
  <% end %>

  <% if @hike.image_credit.present? %>
    <div class="d-flex mt-1">
      <small class="text-muted ms-auto"><%= @hike.image_credit %></small>
    </div>
  <% end %>

  <div class="d-flex align-items-center mt-3">
    <%= render "likes/like", hike: @hike, like: @like %>

    <div class="d-flex gap-2 ms-auto">
      <% if @hike.latitude.present? && @hike.longitude.present? %>
        <%= link_to hike_map_path(@hike), class: "btn btn-outline-primary" do %>
          <i class="bi bi-globe-americas"></i>
          Map
        <% end %>
      <% end %>

      <% if user_signed_in? && @hike.user == current_user %>
        <%= link_to edit_hike_path(@hike), class: "btn btn-outline-primary" do %>
          <i class="bi bi-pencil"></i>
          Edit
        <% end %>
      <% end %>
    </div>
  </div>

  <p class="text-body-secondary mt-4">
    <%= @hike.description %>
  </p>
</div>